analytics: {}
color:
  brandColors:
    - '#9cceff'
    - '#fbecd9'
    - '#6f9eb8'
    - '#0c0c0e'
    - '#50522b'
  brandStrength: 0
  lightness: 0.166222
  rhythmicContrast: 0.460285
  saturation: 0.107191
cta: {}
layout_spectrum: 0.748873
name: AnthonyNTran
opengraph: {}
purpose: []
typography_spectrum: 0
